import Head from "next/head";

import { Inter } from "@next/font/google";

import PostDisplay from "./components/PostDisplay.js";
import Grid from "./components/Grid.js";
import Form from "./components/Form.js";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });
const defaultPostsState = [
  ["this is a post", "this is another post", "this is the last post"],
  ["this a down post", "this is the next down post", "this is last down post"],
  ["this is  post rock bottom post", "this post is next rock bottom", null],
];

export default function Home() {
  const router = useRouter();
  const [postsArray, setPostsArray] = useState(
    router.query.posts ? JSON.parse(router.query.posts) : defaultPostsState
  );

  const [coordinates, setCoordinates] = useState([0, 0]);
  useEffect(() => {
    window.history.pushState(null, null, `?posts=${JSON.stringify(postsArray)}`);
  });
  //hooks go inside component

  return (
    <>
      <Head>
        <title>Comrade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet" />
      </Head>
      <section className="sm:p-20 sm:w-3/5 w-full">
        <div className="text-white px-10"></div>
        <h1 className="text-9xl text-center">Comrade</h1>
        <h2 className="text-3xl p-10 text-center	"> An app to do something</h2>
      </section>
      <div className=" text-white flex flex-col items-center">
        <PostDisplay
          coordinates={coordinates}
          setCoordinates={setCoordinates}
          postsArray={postsArray}
        />
        <Grid setCoordinates={setCoordinates}></Grid>
        <Form
          setPostsArray={setPostsArray}
          postsArray={postsArray}
          coordinates={coordinates}
        ></Form>
      </div>
    </>
  );
}
